---
- name: nginx installation
  hosts: nginx
  become: yes

  tasks:
  - name: copy repo file
    copy:
     src: /etc/yum.repos.d/nginx.repo
     dest: /etc/yum.repos.d/nginx.repo

  - name: nginx yum installation
    yum:
     name: nginx
     state: latest

  -  name: Copying index.html
     template:
      src: ~/ansible/website/index.j2
      dest: /usr/share/nginx/html/index.html

  - name: nginx start enable
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
