---
- name: Firewall Power Off
  hosts: all
  become: yes

  tasks:
  - name: Disable SELinux
    selinux:
     state: disabled

  - name: Disable firewall
    service:
     name: firewalld
     state: stopped  
     enabled: no

  - name: Reboot and reconnect
    reboot:
     connect_timeout: 5
     reboot_timeout: 600
     post_reboot_delay: 120
     test_command: whoami
