---
- name: keepalived installing 
  become: yes
  hosts: haproxy

  tasks:

  - name: keepalived installing
    yum:
     name: keepalived
     state: latest
     
  - name: keepalived.conf copying
    template:
     src: ~/ansible/keepalived/keepalived.j2
     dest: /etc/keepalived/keepalived.conf

  - name: keepalived start & enable
    systemd:
     name: haproxy
     state: started
     enabled: yes


