---
- name: haproxy installing 
  become: yes
  hosts: haproxy

  tasks:

  - name: haproxy installing
    yum:
     name: haproxy
     state: latest

  - name: haproxy start & enable
    systemd:
     name: haproxy
     state: started
     enabled: yes
     
