---
- name: haproxy installing 
  become: yes
  hosts: haproxy

  tasks:

  - name: haproxy installing
    yum:
     name: haproxy
     state: latest
     
  - name: haproxy.cfg copying
    template:
     src: ~/ansible/haproxy/haproxy.j2
     dest: /etc/haproxy/haproxy.cfg

  - name: haproxy start & enable
    systemd:
     name: haproxy
     state: started
     enabled: yes


